### ISSUE TITLE
字体问题，是不是因为源文档本身就是图片

### ISSUE THREAD

**Issue by home0395** [BoyInTheSun/wks#12]
PS C:\wks-0.4> python main.py -c cookie https://wenku.baidu.com/view/1ecc8c984bfe04a1b0717fd5360cba1aa8118ca4.html
Download from https://wenku.baidu.com/view/1ecc8c984bfe04a1b0717fd5360cba1aa8118ca4.html
Download HTML...Success.
Parse HTML...Success.
title:  浅谈仅用无刻度直尺的几何作图题的教与学
Found pdf file, prepare for download...Success.
It seems that you provided incorrect or Non-VIP cookies, only be able to download a part of the file (1 page), not the whole file (4 page).
page:  1
Start downloading font(s)...
|=================================================>| 1 / 1 (100.00%)
Start downloading json(s)...
|=================================================>| 1 / 1 (100.00%)
Start downloading png(s)...
|=================================================>| 1 / 1 (100.00%)
Start generating pdf...
|=================================================>| 1 / 1 (100.00%)Traceback (most recent call last):
  File "C:\Apps\Python3\lib\site-packages\reportlab\pdfbase\pdfmetrics.py", line 697, in getFont
    return _fonts[fontName]
KeyError: 'MingLiU'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\wks-0.4\main.py", line 265, in <module>
    save_pdf(temp_dir, pagenums[i])
  File "C:\wks-0.4\json2pdf.py", line 66, in save_pdf
    textobject.setFont(
  File "C:\Apps\Python3\lib\site-packages\reportlab\pdfgen\textobject.py", line 318, in setFont
    font = pdfmetrics.getFont(self._fontname)
  File "C:\Apps\Python3\lib\site-packages\reportlab\pdfbase\pdfmetrics.py", line 699, in getFont
    return findFontAndRegister(fontName)
  File "C:\Apps\Python3\lib\site-packages\reportlab\pdfbase\pdfmetrics.py", line 681, in findFontAndRegister
    face = getTypeFace(fontName)
  File "C:\Apps\Python3\lib\site-packages\reportlab\pdfbase\pdfmetrics.py", line 638, in getTypeFace
    return _typefaces[faceName]
KeyError: 'MingLiU'

**Comment by BoyInTheSun** [comment]
这篇是百度文库提供的原始数据存在问题，已经解决
