### ISSUE TITLE
可能是字体引起的error？

### ISSUE THREAD

**Issue by 150481878** [BoyInTheSun/wks#3]
在下[这篇](https://wenku.baidu.com/view/800fbae05b8102d276a20029bd64783e08127d6d.html )这篇文章的时候出错，代码如下：

D:\wks>python main.py https://wenku.baidu.com/view/800fbae05b8102d276a20029bd64783e08127d6d.html -C cookies.txt
Download from https://wenku.baidu.com/view/800fbae05b8102d276a20029bd64783e08127d6d.html
Download HTML...Success.
Parse HTML...Success.
title:  气井产能确定方法归类总结
Found word file, prepare for download...Success.
Start downloading font(s)...
|=================================================>| 22 / 22 (100.00%)
Start downloading json(s)...
|=================================================>| 22 / 22 (100.00%)
Start downloading png(s)...
|=================================================>| 22 / 22 (100.00%)
Start generating pdf...
|============================================>-----| 20 / 22 (90.91%)Traceback (most recent call last):
  File "D:\wks\main.py", line 195, in <module>
    save_pdf(temp_dir, i)
  File "D:\wks\json2pdf.py", line 31, in save_pdf
    pdfmetrics.registerFont(TTFont(ttf2font.get(ttf[:-4]), os.path.join(tempdir, ttf)))
  File "D:\Python3\lib\site-packages\reportlab\pdfbase\pdfmetrics.py", line 633, in registerFont
    registerFontFamily(font.fontName)
  File "D:\Python3\lib\site-packages\reportlab\pdfbase\pdfmetrics.py", line 602, in registerFontFamily
    family = family.lower()
AttributeError: 'NoneType' object has no attribute 'lower'

**Comment by BoyInTheSun** [comment]
reportlab对于字体的支持很差，百度文库提供的字体文件还可能有问题，头大

**Comment by BoyInTheSun** [comment]
报错已解决，但是目前中文字体仍显示异常，原因未知，应该是reportlab的bug
